// questions.js

const normal_questions = [
    {"label": "composition", "question": "What can you say about the composition of this work?"},
    {"label": "unity_elements", "question": "On the subject of this painting's composition, what can you say about the unity between the elements?"},
    {"label": "unity_colors", "question": "On the subject of this painting's composition, what can you say about the unity between the colors?"},
    {"label": "balance_elements", "question": "On the subject of this painting's composition, what can you say about the balance between the elements?"},
    {"label": "balance_colors", "question": "On the subject of this painting's composition, what can you say about the balance between the colors?"},
    {"label": "list_elements", "question": "List all the elements that make up this painting."},
    {"label": "describe_elements", "question": "Describe all the elements that make up this painting."},
    {"label": "list_colors", "question": "List all the colors used in this painting."},
    {"label": "describe_colors", "question": "Describe how the different colors are used in this painting."},
    {"label": "movement", "question": "On the subject of this painting's composition, what can you say about the movement depicted?"},
    {"label": "rhythm", "question": "On the subject of this painting's composition, what can you say about the rhythm in the shown elements?"},
    {"label": "focus_point", "question": "On the subject of this painting's composition, what can you say about the focus point?"},
    {"label": "contrast_elements", "question": "On the subject of this painting's composition, what can you say about the contrast between the elements?"},
    {"label": "contrast_colors", "question": "On the subject of this painting's composition, what can you say about the contrast between the colors?"},
    {"label": "patterns", "question": "On the subject of this painting's composition, what can you say about patterns in the arrangement?"},
    {"label": "proportion", "question": "On the subject of this painting's composition, what can you say about the proportion between the elements?"},
    {"label": "edgar_payne", "question": "Edgar Payne, a renowned landscape painter, identified 15 compositional archetypes that artists can use to create visually compelling and balanced paintings. These archetypes are foundational structures or patterns that help in organizing the elements of a composition effectively. Here are Edgar Payne's 15 compositional archetypes: Steelyard, Balance Scale, Circle, S-Curve, L-Shape, Compound Curve, Radiating Lines, Triangle, Pyramid, Cross, Diagonal, Rectangular, O, Tunnel, Radiating Curve. Can you identify which archetype is used in this painting?"},
    {"label": "foreground_background_1", "question": "What can you say about the relationship between the foreground and background in this painting?"},
    {"label": "foreground_background_2", "question": "What can you say about the relationship between the foreground and background in this painting? Use keywords as 'The use of foreground/background relationship in the composition'"},
    {"label": "foreground_background_3", "question": "What can you say about the relationship between the foreground and background in the composition?"},
    {"label": "foreground_background_3", "question": "How do you describe the relationship between the foreground and background in the composition?"},
    {"label": "foreground_background_4", "question": "What can you say about the foreground/background relationship in the composition?"},
    {"label": "ground_figure_1", "question": "What can you say about the relationship between the ground and figure in this painting?"},
    {"label": "ground_figure_2", "question": "What can you say about the relationship between the ground and figure in this painting? Use keywords as 'The use of figure/ground relationship in the composition'"},
    {"label": "ground_figure_3", "question": "What can you say about the relationship between the ground and figure in the composition?"},
    {"label": "ground_figure_3", "question": "How do you describe the relationship between the ground and figure in the composition?"},
    {"label": "ground_figure_4", "question": "What can you say about the ground/figure relationship in the composition?"},
    {"label": "open_closed_1", "question": "Describe whether the composition is open or closed and how did you come to this conclusion."},
    {"label": "open_closed_2", "question": "A closed composition in art means that all the elements within the painting are arranged in such a way that they direct the viewer's attention back into the artwork itself, rather than leading the eye out of the frame.  An open composition, on the other hand, is designed to lead the viewer's eye out of the painting, giving a sense that the scene continues beyond the canvas. This style creates a more dynamic and less constrained feeling. Describe whether the composition is open or closed and why."},
    {"label": "open_closed_3", "question": "What can you say about the open/closed composition in this painting?"},
    {"label": "open_closed_4", "question": "How do you describe the open/closed composition in the painting?"},
    {"label": "symmetry_asymmetry_1", "question": "Describe whether the composition is symmetrical or asymmetrical and why."},
    {"label": "symmetry_asymmetry_2", "question": "Symmetry is a balanced arrangement of elements on either side of a central axis. Asymmetry is an unbalanced arrangement of elements. Describe whether the composition is symmetrical or asymmetrical and how you came to this conclusion."},
    {"label": "symmetry_asymmetry_3", "question": "What can you say about the symmetry/asymmetry in this painting?"},
    {"label": "symmetry_asymmetry_4", "question": "How do you describe the symmetry/asymmetry in the painting?"},
    {"label": "rule_thirds_1", "question": "Describe whether the rule of thirds is used in this painting and why."},
    {"label": "rule_thirds_2", "question": "The rule of thirds is a compositional rule of thumb in visual arts such as painting, photography and design. The rule states that an image should be divided into nine equal parts by two equally spaced horizontal lines and two equally spaced vertical lines, and that important compositional elements should be placed along these lines or their intersections. Describe whether the rule of thirds is used in this painting."},
    {"label": "rule_thirds_3", "question": "What can you say about the use of rule of thirds in this painting?"},
    {"label": "rule_thirds_4", "question": "How do you describe the use of rule of thirds in the painting?"},
    {"label": "golden_ratio_1", "question": "Describe whether the golden ratio is used in this painting and why."},
    {"label": "golden_ratio_2", "question": "The golden ratio is a special number found by dividing a line into two parts so that the longer part divided by the smaller part is also equal to the whole length divided by the longer part. The golden ratio is approximately equal to 1.618. Describe whether the golden ratio is used in this painting and how."},
    {"label": "golden_ratio_3", "question": "What can you say about the use of golden ratio in this painting?"},
    {"label": "leading_lines_1", "question": "Describe whether leading lines are used in this painting and how."},
    {"label": "leading_lines_2", "question": "Leading lines are lines within an image that leads the eye to another point in the image, or occasionally, out of the image. Anything with a definite line can be a leading line. Describe whether leading lines are used in this painting and how."},
    {"label": "leading_lines_3", "question": "What can you say about the leading lines in this painting?"},
    {"label": "leading_lines_4", "question": "How do you describe the leading lines in the painting?"},
    {"label": "gestalt_principles_1", "question": "Can you explain if and how gestalt principles are applied in this painting?"},
    {"label": "gestalt_principles_2", "question": "Gestalt principles in art composition are a set of theories developed in psychology to explain how humans naturally perceive visual elements as organized patterns or wholes, rather than as separate components. These principles are often applied in art and design to create compositions that are visually appealing and well-organized. Can you discuss their application in this composition?"},
    {"label": "gestalt_principles_3", "question": "What observations can you make about the use of gestalt principles in this artwork?"},
    {"label": "gestalt_principles_4", "question": "How would you describe the application of gestalt principles in this painting?"},
    {"label": "perspective_1", "question": "Describe the use of perspective in this composition."},
    {"label": "lines_composition_1", "question": "Can you tell something about the use of lines in this composition in words of quality, direction, pressure, and width?"},
    {"label": "lines_composition_2", "question": "What can you say about lines in this composition in terms of quality, direction, pressure, and width?"},
    {"label": "lines_composition_3", "question": "What can you say about the use of lines in this composition?"},
    {"label": "eye_movement", "question": "How does the composition of this painting guide the viewer's eye movement?"},
    {"label": "eye_movement_2", "question": "How is the viewer's eye movement guided in this composition?"},
    {"label": "eye_movement_3", "question": "How is the viewer's eye movement guided in this composition and what elements contribute to this?"}
];


if (typeof module !== 'undefined' && typeof module.exports !== 'undefined') {
    module.exports = questions;
}

